---
Name: masqueradeconfig
---
SilverStripe\Admin\SecurityAdmin:
  extensions:
    - DHensby\SilverStripeMasquerade\Extensions\SecurityAdminExtension
SilverStripe\Security\Member:
  extensions:
    - DHensby\SilverStripeMasquerade\Extensions\MemberExtension
---
Name: masquerademiddleware
After:
  - '#session-manager-middleware'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        MasqueradeMiddleware: '%$DHensby\SilverStripeMasquerade\Control\MasqueradeMiddleware'
SilverStripe\Security\MemberAuthenticator\LogoutHandler:
  extensions:
    - DHensby\SilverStripeMasquerade\Extensions\LogoutHandlerExtension
